language: c++

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get -y install qt5-default 

script:
  - qmake
  - make
