language: cpp

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install qt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get -y install qt5-default ; fi

script:
  - qmake
  - make
